/* Generates js/tkshim.js from py/tkinter_shim.py.
   The shim is embedded as window.__TKINTER_SHIM so the IDE works
   when index.html is opened directly via file:// (no fetch allowed).
   Run with: node tools/gen_shim.js */
const fs = require('fs');
const path = require('path');

const py = fs.readFileSync(path.join(__dirname, '..', 'py', 'tkinter_shim.py'), 'utf8');
const out =
  '/* AUTO-GENERATED by tools/gen_shim.js from py/tkinter_shim.py — do not edit by hand. */\n' +
  'window.__TKINTER_SHIM = ' + JSON.stringify(py) + ';\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'tkshim.js'), out);
console.log('wrote js/tkshim.js (' + out.length + ' bytes)');
